modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="evil_chicken"
version="1.0.0"
displayName="Evil Chicken"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="rollylindenshnizzer"
authors="rollylindenshnizzer"
description="Adds a very evil chicken to Minecraft. Watch out."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.evil_chicken]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.evil_chicken]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration